// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.9.3-477-g7b0a020a-dirty"
#define MICROPY_GIT_HASH "7b0a020a-dirty"
#define MICROPY_BUILD_DATE "2018-03-25"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (9)
#define MICROPY_VERSION_MICRO (3)
#define MICROPY_VERSION_STRING "1.9.3"
